|
  apiVersion: apps/v1
  kind: Deployment
  metadata:
   name: {{ include "confixa-redis.fullname" . }}-light
   labels:
   {{- include "confixa-redis.labels" . | nindent 4 }}
  spec:
   replicas: {{ .Values.replicaCountLight }}
   selector:
   matchLabels:
   {{- include "confixa-redis.selectorLabels" . | nindent 6 }}
   template:
   metadata:
   labels:
   {{- include "confixa-redis.labels" . | nindent 8 }}
   spec:
   containers:
   - name: {{ .Chart.Name }}
   image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
   imagePullPolicy: {{ .Values.image.pullPolicy }}
   ports:
   - name: http
   containerPort: {{ .Values.service.port }}
   protocol: TCP
   resources:
   {{- toYaml .Values.resourcesLight | nindent 12 }}
