|
  apiVersion: autoscaling/v2
  kind: HorizontalPodAutoscaler
  metadata:
   name: {{ include "confixa-redis.fullname" . }}-light
   labels:
   {{- include "confixa-redis.labels" . | nindent 4 }}
  spec:
   scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: {{ include "confixa-redis.fullname" . }}-light
   minReplicas: {{ .Values.autoscalingLight.minReplicas }}
   maxReplicas: {{ .Values.autoscalingLight.maxReplicas }}
   metrics:
   - type: Resource
   resource:
   name: cpu
   target:
   type: Utilization
   averageUtilization: {{ .Values.autoscalingLight.targetCPUUtilizationPercentage }}
