name: Issue Creation Workflow

on:
 issues:
   types: [opened]

jobs:

 process-issue:
   runs-on: ubuntu-latest
   
   steps:
   - uses: actions/checkout@v3
     with:
       fetch-depth: 0
       
   - name: Create Branch
     run: |
       BRANCH_NAME="issue-${{ github.event.issue.number }}"
       git checkout -b "$BRANCH_NAME"
       
