name: Issue Creation Workflow

on:
 issues:
   types: [opened]

jobs:

 process-issue:
   runs-on: ubuntu-latest
   
   steps:
   - uses: actions/checkout@v3
     with:
       fetch-depth: 0

   - name: Configure Git User
     run: |
       git config --global user.name "${{ github.event.user.name || 'GitHub Actions Bot' }}"
       git config --global user.email "${{ github.event.user.email || 'github-actions@users.noreply.github.com' }}"
       git remote set-url origin https://${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}
   
       echo "git config --global user.name: ${{ github.event.user.name || 'GitHub Actions Bot' }}"
       echo "git config --global user.email: ${{ github.event.user.email || 'github-actions@users.noreply.github.com' }}"
       echo "git remote set-url origin: https://${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}"

   - name: Create Branch
     run: |
       BRANCH_NAME="issue-${{ github.event.issue.number }}"
       git checkout -b "$BRANCH_NAME"

   - name: Commit Branch
     run: |
       git config --global user.name '$GITHUB_ACTOR'
       git config --global user.email '$GITHUB_ACTOR@wohlig.com'
       git commit --allow-empty -m "Created branch for issue #${{ github.event.issue.number }}"
       
   - name: Push Branch
     run: |
       BRANCH_NAME="issue-${{ github.event.issue.number }}"
       git push --set-upstream origin "$BRANCH_NAME"
       
